### ISSUE TITLE
Isolate vc indexes from other ES indexes

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/daf-anpr-api#7]
## Reproduce

- create indexes on Elastic
- run daf-anpr-api
- create more indexes on the same Elastic instance, unrelated to daf-anpr-api

## I expect

- daf-anpr-api shows only selected indexes

## instead

- daf-anpr-api shows all non blacklisted indexes

## hint

profile the app with user visibility

@fabiofumarola hints welcome

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
